site_name: lensboy
site_description: A practical guide to camera calibration with lensboy
site_url: https://robertleoj.github.io/lensboy/
repo_url: https://github.com/Robertleoj/lensboy
repo_name: Robertleoj/lensboy

use_directory_urls: false

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  features:
    - content.code.copy
    - navigation.sections

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-Q00T2DD53Y

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Calibration Guide: calibration_guide.md
  - Unproject LUT: unproject_lut.md
