"""
lensboy for camera calibration
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['PinholeSplinedIntrinsicsParameters', 'PinholeSplinedModelDefinition', 'PinholeSplinedOptimizationConfig', 'WarpCoordinates', 'add', 'calibrate_opencv', 'fine_tune_pinhole_splined', 'get_matching_spline_distortion_model', 'get_matching_stereographic_opencv_model', 'make_undistortion_maps_pinhole_splined', 'max_cell_errors_opencv', 'max_cell_errors_pinhole_splined', 'normalize_pinhole_splined_points', 'project_pinhole_splined_points', 'seeded_normalize_opencv', 'seeded_normalize_splined', 'set_log_level', 'warp_target_points']
class PinholeSplinedIntrinsicsParameters:
    def __init__(self, pinhole_parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], dx_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], dy_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def dx_grid(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @dx_grid.setter
    def dx_grid(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    @property
    def dy_grid(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @dy_grid.setter
    def dy_grid(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    @property
    def pinhole_parameters(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @pinhole_parameters.setter
    def pinhole_parameters(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
class PinholeSplinedModelDefinition:
    def __init__(self, image_width: typing.SupportsInt, image_height: typing.SupportsInt, fov_deg_x: typing.SupportsFloat, fov_deg_y: typing.SupportsFloat, num_knots_x: typing.SupportsInt, num_knots_y: typing.SupportsInt) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def fov_deg_x(self) -> float:
        ...
    @fov_deg_x.setter
    def fov_deg_x(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def fov_deg_y(self) -> float:
        ...
    @fov_deg_y.setter
    def fov_deg_y(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def image_height(self) -> int:
        ...
    @image_height.setter
    def image_height(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def image_width(self) -> int:
        ...
    @image_width.setter
    def image_width(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_knots_x(self) -> int:
        ...
    @num_knots_x.setter
    def num_knots_x(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_knots_y(self) -> int:
        ...
    @num_knots_y.setter
    def num_knots_y(self, arg0: typing.SupportsInt) -> None:
        ...
class PinholeSplinedOptimizationConfig(PinholeSplinedModelDefinition):
    def __init__(self, image_width: typing.SupportsInt, image_height: typing.SupportsInt, fov_deg_x: typing.SupportsFloat, fov_deg_y: typing.SupportsFloat, num_knots_x: typing.SupportsInt, num_knots_y: typing.SupportsInt, smoothness_lambda: typing.SupportsFloat) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def smoothness_lambda(self) -> float:
        ...
    @smoothness_lambda.setter
    def smoothness_lambda(self, arg0: typing.SupportsFloat) -> None:
        ...
class WarpCoordinates:
    def __init__(self, target_from_warp_frame: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"], x_scale: typing.SupportsFloat, y_scale: typing.SupportsFloat) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def target_from_warp_frame(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
    @target_from_warp_frame.setter
    def target_from_warp_frame(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> None:
        ...
    @property
    def x_scale(self) -> float:
        ...
    @x_scale.setter
    def x_scale(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def y_scale(self) -> float:
        ...
    @y_scale.setter
    def y_scale(self, arg0: typing.SupportsFloat) -> None:
        ...
def add(a: typing.SupportsInt, b: typing.SupportsInt) -> int:
    """
    Add two integers together - test
    """
def calibrate_opencv(intrinsics_initial_value: collections.abc.Sequence[typing.SupportsFloat], intrinsics_param_optimize_mask: collections.abc.Sequence[bool], cameras_from_target: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]], target_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], frames: collections.abc.Sequence[tuple[collections.abc.Sequence[typing.SupportsInt], collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]]]], warp_coordinates: WarpCoordinates | None = None, warp_coeffs_initial: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat], "FixedSize(5)"] = [0.0, 0.0, 0.0, 0.0, 0.0]) -> dict:
    ...
def fine_tune_pinhole_splined(model_config: PinholeSplinedOptimizationConfig, intrinsics_parameters: PinholeSplinedIntrinsicsParameters, cameras_from_target: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]], target_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], frames: collections.abc.Sequence[tuple[collections.abc.Sequence[typing.SupportsInt], collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]]]], warp_coordinates: WarpCoordinates | None = None, warp_coeffs_initial: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat], "FixedSize(5)"] = [0.0, 0.0, 0.0, 0.0, 0.0]) -> dict:
    ...
def get_matching_spline_distortion_model(opencv_distortion_params: collections.abc.Sequence[typing.SupportsFloat], model_config: PinholeSplinedOptimizationConfig, image_bound_x: typing.SupportsFloat, image_bound_y: typing.SupportsFloat) -> dict:
    ...
def get_matching_stereographic_opencv_model(image_width: typing.SupportsInt, image_height: typing.SupportsInt, stereographic_focal_length: typing.SupportsFloat, distortion_param_optimize_mask: collections.abc.Sequence[bool]) -> dict:
    ...
def make_undistortion_maps_pinhole_splined(model_config: PinholeSplinedModelDefinition, intrinsics: PinholeSplinedIntrinsicsParameters, pinhole_parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], image_size_wh: tuple[typing.SupportsInt, typing.SupportsInt]) -> tuple:
    ...
def max_cell_errors_opencv(intrinsics: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], lut_xy_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], image_width: typing.SupportsInt, image_height: typing.SupportsInt, interpolation_mode: typing.SupportsInt, max_iterations: typing.SupportsInt, gradient_tolerance: typing.SupportsFloat) -> numpy.typing.NDArray[numpy.float64]:
    ...
def max_cell_errors_pinhole_splined(config: PinholeSplinedModelDefinition, intrinsics: PinholeSplinedIntrinsicsParameters, lut_xy_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], image_width: typing.SupportsInt, image_height: typing.SupportsInt, interpolation_mode: typing.SupportsInt, max_iterations: typing.SupportsInt, gradient_tolerance: typing.SupportsFloat) -> numpy.typing.NDArray[numpy.float64]:
    ...
def normalize_pinhole_splined_points(model_config: PinholeSplinedModelDefinition, intrinsics: PinholeSplinedIntrinsicsParameters, pixel_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
    ...
def project_pinhole_splined_points(model_config: PinholeSplinedModelDefinition, intrinsics: PinholeSplinedIntrinsicsParameters, points_in_camera: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
    ...
def seeded_normalize_opencv(seed_pixels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], seed_normals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], seed_width: typing.SupportsInt, seed_height: typing.SupportsInt, query_pixels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], intrinsics: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
    ...
def seeded_normalize_splined(seed_pixels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], seed_normals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], seed_width: typing.SupportsInt, seed_height: typing.SupportsInt, query_pixels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], config: PinholeSplinedModelDefinition, intrinsics: PinholeSplinedIntrinsicsParameters) -> numpy.typing.NDArray[numpy.float64]:
    ...
def set_log_level(level: str) -> None:
    ...
def warp_target_points(warp_coordinates: WarpCoordinates, warp_coeffs: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], target_points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
    ...
